In [1]:
# 「Hello World」 표시
print('Hello World')

Hello World


In [2]:
a = 1
b = 2
c = a + b
print (a, b, c)

1 2 3


In [3]:
a = 11
s = 'a는 10이상' if a > 10 else  'a는 10미만'
print (s)

a는 10이상


In [4]:
text = '''텍스트 첫 번째 행.
텍스트 두 번째 행.'''
print(text)

텍스트 첫 번째 행.
텍스트 두 번째 행


In [5]:
print('문자열' + ' 결합')

문자열 결합


In [6]:
print('정답 = ' + str(100))

정답 = 100


In [7]:
text = 'Hello World'
print(text[1:3])
print(text[:5])
print(text[6:])

el
Hello
World


In [8]:
a = 'Test'
b = 100
c = 3.14159

print('문자열 = {}'.format(a))
print('정수 = {}'.format(b))
print('부동소수점수 = {}'.format(c))
print('부동소수점수(소수점2자리) = {:.2f}'.format(c))
print ('여러 변수 = {}, {}, {:.2f}'.format(a, b, c))

문자열 = Test
정수 = 100
부동소수점수 = 3.14159
부동소수점수(소수점2자리) = 3.14
여러 변수 = Test, 100, 3.14


In [9]:
my_list = [1, 2, 3, 4]
print(my_list)
print(my_list[0])
print(my_list[1:3])

[1, 2, 3, 4]
1
[2, 3]


In [10]:
my_list = [1, 2, 3, 4]
my_list[0] = 10
print(my_list)
my_list[1:4] = [20, 30]
print(my_list)

[10, 2, 3, 4]
[10, 20, 30]


In [11]:
my_list = ['Apple', 'Cherry']
print(my_list)
my_list.append('Strawberry')
print(my_list)
del my_list[1]
print(my_list)
my_list.remove('Apple')
print(my_list)

['Apple', 'Cherry']
['Apple', 'Cherry', 'Strawberry']
['Apple', 'Strawberry']
['Strawberry']


In [12]:
print(list(range(10)))
print(list(range(1, 7)))
print(list(range(1, 10, 2)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6]
[1, 3, 5, 7, 9]


In [13]:
my_dic= {'Apple': 300, 'Cherry': 200, 'Strawberry': 3000}
print(my_dic['Apple'])

300


In [14]:
my_dic['Apple'] = 400
print(my_dic)

{'Apple': 400, 'Cherry': 200, 'Strawberry': 3000}


In [15]:
my_dic = {'Apple' : 300}
print(my_dic)
my_dic['Cherry'] = 200
print(my_dic)
del my_dic['Apple']
print(my_dic)

{'Apple': 300}
{'Apple': 300, 'Cherry': 200}
{'Cherry': 200}


In [16]:
my_taple = (1, 2, 3, 4)
print(my_taple)
print(my_taple[0])
print(my_taple[1:3])

(1, 2, 3, 4)
1
(2, 3)


In [17]:
num = 5
if num >= 10:
    print('num이 10이상') # 조건 성립
else:
    print('num이 10미만') # 조건 미성립

num이 10미만


In [18]:
num = 10
if num >= 5:
    print('num이 5이상') # 1번째 조건 성립
elif num >= 3:
    print('num이 3이상') # 2번째 조건 성립
else:
    print('num이 3미만') # 조건 미성립

num이 5이상


In [19]:
for n in [1, 2, 3]:
    print(n), # 반복 대상
    print(n*10) # 반복 대상

1
10
2
20
3
30


In [20]:
for n in range(5):
    print(n), # 반복 대상

0
1
2
3
4


In [21]:
i = 0
while i < 20:
    i += 1
    if i % 2 == 0:
        continue
    if i % 3 == 0:
        print(i)

3
9
15


In [22]:
for num, fruit in enumerate(['Apple', 'Cherry', 'Strawberry']):
    print('{}:{}'.format(num, fruit))

0:Apple
1:Cherry
2:Strawberry


In [23]:
my_list1 = []
for x in range(10):
    my_list1.append(x * 2)

print(my_list1)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [24]:
my_list2 = [x * 2 for x in range(10)]

print(my_list2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [25]:
def radian(x):
    return x / 180 * 3.1415

for x in range(0, 360, 90):
    print('각도: {}, 라디안: {:.2f}'.format(x, radian(x)))

각도: 0, 라디안: 0.00
각도: 90, 라디안: 1.57
각도: 180, 라디안: 3.14
각도: 270, 라디안: 4.71


In [26]:
lambda_radian = (lambda x:x / 180 * 3.1415)

for x in range(0, 360, 90):
    print('각도: {}, 라디안: {:.2f}'.format(x, lambda_radian(x)))

각도: 0, 라디안: 0.00
각도: 90, 라디안: 1.57
각도: 180, 라디안: 3.14
각도: 270, 라디안: 4.71


In [27]:
class HelloClass:
    def __init__(self, msg):
        self.msg = msg

    def output(self):
        print(self.msg)

hello = HelloClass('Hello World')
hello.output()

Hello World


In [28]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
from numpy import array

a = array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
